name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        services:
            mongo:
                image: mongo:6.0
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: actions/checkout@v4

            - name: Установка Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 23

            - name: Установка зависимостей backend
              run: npm ci

            - name: Линтинг backend
              run: npm run lint

            - name: Тесты backend
              run: npm test

            - name: Установка зависимостей frontend
              run: |
                  cd client
                  npm ci

            - name: Линтинг frontend
              run: |
                  cd client
                  npm run lint

            - name: Тесты frontend
              run: |
                  cd client
                  npm test -- --watchAll=false

            - name: Сборка frontend
              run: |
                  cd client
                  npm run build

            - name: Проверка структуры проекта
              run: |
                  test -d client && test -f app.js && test -f README.md && test -f .gitignore && echo "Структура в порядке"
